{
  "formatVersion": "1.1",
  "component": {
    "group": "org.chargebee.spi",
    "module": "cb-provider-spi",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cb-provider-spi-0.0.12.jar",
          "url": "cb-provider-spi-0.0.12.jar",
          "size": 543721,
          "sha512": "e831ce28b3e8f36b18de9584e0f9ac60014b16963bbc245b40f62e078c9a0560c8792c4d009c635cd23edbeb1c3408fec41ff57cea04c16fbd15026e35b9d822",
          "sha256": "2df9387ec6e8e008903cac489b09ae164754840a9acfb5dcfeaca737416674b1",
          "sha1": "aef6fe8f17eb75536eda9b1f126f240311e4b098",
          "md5": "25ed3c144d99f6281d6844168074d79e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.gsonfire",
          "module": "gson-fire",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "javax.ws.rs",
          "module": "jsr311-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "javax.ws.rs",
          "module": "javax.ws.rs-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20231013"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "cb-provider-spi-0.0.12.jar",
          "url": "cb-provider-spi-0.0.12.jar",
          "size": 543721,
          "sha512": "e831ce28b3e8f36b18de9584e0f9ac60014b16963bbc245b40f62e078c9a0560c8792c4d009c635cd23edbeb1c3408fec41ff57cea04c16fbd15026e35b9d822",
          "sha256": "2df9387ec6e8e008903cac489b09ae164754840a9acfb5dcfeaca737416674b1",
          "sha1": "aef6fe8f17eb75536eda9b1f126f240311e4b098",
          "md5": "25ed3c144d99f6281d6844168074d79e"
        }
      ]
    }
  ]
}
