/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.api.openapilocationvalidationyml;

import com.example.model.openapilocationvalidationyml.BasicErrorResponse;
import com.example.model.openapilocationvalidationyml.HealthCheckResponse;
import com.example.model.openapilocationvalidationyml.LocationValidateErrorResponse;
import com.example.model.openapilocationvalidationyml.LocationValidateResponse;
import com.example.model.openapilocationvalidationyml.LocationValidationEvidence;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-10-01T11:22:38.152028+05:30[Asia/Kolkata]")
@Validated
@Tag(name = "LocationValidate", description = "Endpoints to validate the location of the end customer.")
public interface ValidateLocationApi {

    /**
     * POST /validate-location : Validate the location of customer with given evidences
     * This endpoint validates the location of a customer using the evidences like ip, bin, address, etc. to determine if a customer is taxable or not.
     *
     * @param locationValidationEvidence  (optional)
     * @return Response to validate the location submitted successfully. (status code 200)
     *         or Bad request. (status code 400)
     *         or Unauthenticated request. (status code 401)
     *         or Unauthorized request. (status code 403)
     *         or Too many requests. (status code 429)
     *         or Unexpected error while processing request. (status code 500)
     *         or Service is unhealthy. (status code 503)
     */
    @Operation(
        operationId = "locationValidate",
        summary = "Validate the location of customer with given evidences",
        description = "This endpoint validates the location of a customer using the evidences like ip, bin, address, etc. to determine if a customer is taxable or not.",
        tags = { "LocationValidate" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Response to validate the location submitted successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationValidateResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationValidateErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthenticated request."),
            @ApiResponse(responseCode = "403", description = "Unauthorized request."),
            @ApiResponse(responseCode = "429", description = "Too many requests."),
            @ApiResponse(responseCode = "500", description = "Unexpected error while processing request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BasicErrorResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service is unhealthy.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HealthCheckResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "apiKey"),
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/validate-location",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<LocationValidateResponse> locationValidate(
        @Parameter(name = "LocationValidationEvidence", description = "") @Valid @RequestBody(required = false) LocationValidationEvidence locationValidationEvidence
    );

}
